services:
  web:
    container_name: kintore-web-1
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: kintore-web:latest
    ports:
      - "8080:8080"
    volumes:
      - data:/app/data
    restart: unless-stopped

volumes:
  data:
